project:
  type: website
  output-dir: docs

website:
  title: "Tien Loc Profile"
  favicon: favicon.png
  navbar:
    logo: favicon.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


editor: visual

